base_url = "https://tduyng.com"
feed_url = "https://tduyng.com/atom.xml"
title = "Duy NG"
description = "Software Engineer"
language = "en"
output_dir = "public"

#=========================================================================================
[extra]
name = "Duy NG"
id = "tduyng"
bio = "Software Engineer"
avatar = "/img/avatar.webp"
img = "/img/feed.webp"
links = [
  { name = "GitHub", icon = "github", url = "https://github.com/tduyng" },
  { name = "Twitter", icon = "twitter", url = "https://x.com/tduyng" },
  { name = "Email", icon = "email", url = "mailto:hi@tduyng.com" },
]
sections = [
  { name = "blog", path = "/blog", is_external = false },
  { name = "notes", path = "/notes", is_external = false },
  { name = "about", path = "/about", is_external = false },
]
footer_menu = [
  { name = "tags", path = "/tags", is_external = false },
  { name = "subscribe", path = "/subscribe", is_external = false },
  { name = "contact", path = "/contact", is_external = false },
  { name = "privacy", path = "/privacy", is_external = false },
  { name = "rss", path = "/atom.xml", is_external = false },
]
nav_separator = "☰"
nav_wrapper_left = "["
nav_wrapper_right = "]"
nav_wrapper_separator = ","
ended_words = "Thanks for reading! This writing style focuses on clarity and simplicity, explaining concepts in accessible terms rather than pursuing strict academic precision. If you notice anything outdated, feel free to comment or send me a message."
reaction_align = "right" # "left" | "center" | "right"
reaction_endpoint = "https://reaction.tienduy-nguyen-dev.workers.dev"
footer_copyright = "©2025 Duy NG"
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."
