base_url = "https://tduyng.com"
title = "Duy NG"
description = "Duy NG is Software Engineer, Typescript and Rust enthusiast"
author = "Duy NG"
default_language = "en"
output_dir = "public"
compile_sass = true
minify_html = true
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================
[extra]

name = "Duy NG"
id = "tduyng"
bio = "Software Engineer"
avatar = "/img/avatar.webp"
links = [
  { name = "GitHub", icon = "github", url = "https://github.com/tduyng" },
  { name = "Twitter", icon = "twitter", url = "https://x.com/tduyng" },
  { name = "Email", icon = "email", url = "mailto:hi@tduyng.com" },
]
theme_color = "aurora" #  aurora | bluloco | cosmic_sunset | dracula | electric_tear | halcyon | nebula_bloom | neon_azure | one_dark | sapphire | tokyo_night

#=========================================================================================
# Sharing buttons
enable_sharing = true
enable_word_count = true

# about: displays markdown content of your myblog/content/_index.md
# list: the whole post list, can be categorized
# recent: only a few recent posts
homepage_layout = "recent"

recent_max = 10
recent_more = true
recent_more_text = "All posts »"

sections = [
  { name = "blog", path = "/blog", is_external = false },
  { name = "notes", path = "/notes", is_external = false },
  { name = "about", path = "/about", is_external = false },
]
blog_section_path = "/blog"
about_section_path = "/about"
nav_separator = "::"
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","
footer_menu = [
  { name = "tags", path = "/tags", is_external = false },
  { name = "subscribe", path = "/subscribe", is_external = false },
  { name = "contact", path = "/contact", is_external = false },
  { name = "privacy", path = "/privacy", is_external = false },
]
ended_words = "Thanks for reading! This writing style focuses on clarity and simplicity, explaining concepts in accessible terms rather than pursuing strict academic precision. If you notice anything outdated, feel free to comment or send me a message."
display_id = true        # Whether to display your id on homepage
blog_categorized = false # Whether to categorize blog posts
blur_effect = true       # Whether to turn on blur effect on navigation bar
back_to_top = true       # Whether to show back-to-top button on post pages

toc = true  # Whether to show Table-Of-Contents by default
copy = true # Whether to add a copy button on code blocks by default

reaction = false                                                      # Whether to show reaction (Note: You need to set up a working api endpoint to enable reaction)
reaction_align = "right"                                              # "left" | "center" | "right"
reaction_endpoint = "https://reaction.tienduy-nguyen-dev.workers.dev"

display_tags = true      # Whether to display tags on post pages by default
truncate_summary = false # Whether to truncate the summary of a post by default

outdate_alert = false                                          # Whether to show outdate alert by default
outdate_alert_days = 365                                       # How many days will a post be outdated by default
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

footer_copyright = "©2020-2025 Duy NG"
footer_credits = false

not_found_title = "404"
not_found_error_text = "Not Found"
not_found_recover_text = "« back to home »"
